### ISSUE TITLE
여러개의 파일을 열였다 닫았을때 프로그램이 멈추는 현상 1번

### ISSUE THREAD

**Issue by hi763** [realmani0/special_CD#1]
[특수교과서 선생님들이 다음과 같은 순서로 작업을 할 경우 프로그램이 멈추는 현상이 발생합니다.]

1. 이북을 연 후 우측 이동 화살표를 연속으로 클릭시 프로그램이 멈추는 현상이 발생
2. 메모리가 적은 PC일수록, 용량이 큰 파일을 로딩할수록 현상이 자주 등장

작업 선생님들이 멈춤 현상이 나타나는 부분을 따로 체크해 주셨습니다.
예) 
5단원: 10번째 동영상 다음에서 멈추는 현상 발생
6단원: (동영상 참조) 13번째 동영상 다음 장에서 멈추는 현상 발생
7단원: 10번째 동영상 다음 장에서 멈추는 현상 발생

[https://www.dropbox.com/s/s6nf4tliv4k1lfg/with%20stopping%20video.MOV?dl=0](url)

**Comment by realmani0** [comment]
1.이북을 연 후 우측 이동 화살표를 연속으로 클릭시 프로그램이 멈추는 현상이 발생
- 현 개발자 PC에서는 전혀 나타나지 않음.

2.메모리가 적은 PC일수록, 용량이 큰 파일을 로딩할수록 현상이 자주 등장
- PC환경이 개인마다 다르기 때문에, 메모리 부족으로 발생할 가능성은 있음.

**Comment by realmani0** [comment]
현재 테스트한 현상만으로 봤을때..
windows 10에서 동영상을 2개 실행했을 경우...프로그램이 멈춤 현상이 발생

**Comment by realmani0** [comment]
동영상을 2개 실행했을 경우...프로그램이 멈춤 현상이 발생
- 폼 팝업을 한개씩만 열수 있도록 수정
