### ISSUE TITLE
여러개의 파일을 열였다 닫았을때 프로그램이 멈추는 현상 2번

### ISSUE THREAD

**Issue by hi763** [realmani0/special_CD#2]
[내부 테스트 내용]

1. 실제 콘텐츠 돋보기를 사용 하여 창을 열고 최소화(닫지 않고)하고 다른 창을 계속 열면,  새로 열리는 창의 콘텐츠 내용이 보이지 않고 로딩 되기만 합니다.

2. 동영상 콘텐츠의 경우 창을 열었다, 닫았다를 반복하면 화면이 멈추는 현상이 발생 합니다.

**Comment by realmani0** [comment]
1.실제 콘텐츠 돋보기를 사용 하여 창을 열고 최소화(닫지 않고)하고 다른 창을 계속 열면, 새로 열리는 창의 콘텐츠 내용이 보이지 않고 로딩 되기만 합니다.
- 재현 필요

2.동영상 콘텐츠의 경우 창을 열었다, 닫았다를 반복하면 화면이 멈추는 현상이 발생 합니다.
- 신규 exe 버전으로 테스트 요청드려요.

**Comment by realmani0** [comment]
1. V3 백신이 PC에서 설치되어 있을 경우 나타나는 증상으로
아래처럼 처리하면 발생하지 않음
![v3off_02](https://cloud.githubusercontent.com/assets/23731844/20820866/db9300be-b881-11e6-828a-3e67f49bcf66.png)

2. 특정 동영상에서만 해당 현상이 일어나, 동영상을 다시 인코딩후 테스트한 경우 멈추는 현상이 발생하지 않음
