### ISSUE TITLE
동영상 관련 내용

### ISSUE THREAD

**Issue by hi763** [realmani0/special_CD#3]
[업체 수정 요청]
1. 동영상 재생 중에 창을 닫으면 소리가 계속 나는 현상
재현 영상: [https://www.dropbox.com/s/wzxlkdfmq4shd0z/without%20stopping%20video.MOV?dl=0](url)

[내부 검수]
1. 동영상이 로드되기 전에 하단의 재생스크롤바를 이동하면 동영상 화면이 멈추고 하단 메뉴를 조작할 수 없습니다.(전체 화면 보기, 정지, 이전 시디대로 이동 하기, 재생하기 안됨)

2. 동영상 파일이 로드되기 전에 재생크로롤바를 이동 하고 창을 닫으면,
    닫힌창의 영상 사운드가 계속 나옵니다.

3. 동영상 파일이 로드전에 재생크롤 바를 이동하고 창을 닫고 난 뒤, 새로운 페이지를 열면 멈추는 현상이 발생 합니다.

4. 검수를 오랜 시간 보고 나면 페이지 로딩이 오래 걸리는 현상이 있습니다.

**Comment by realmani0** [comment]
- 동영상 창을 닫을때 무음으로 대체하여 소리가 계속나는 현상 제거
