### ISSUE TITLE
메모리 관련 

### ISSUE THREAD

**Issue by hi763** [realmani0/special_CD#4]
1. 창을 열고 난 뒤 닫을때 마다 메모리 사용량이 증가합니다. 

2. 동영상을 재생한 뒤 창을 닫고 다른 동영상을 재생하면 메모리 사용량이 크게 올라가지는 않지만, 그래도 용량이 올라 갑니다.

3. ebook에서 다음 페이지 이동 버튼을 누를 경우 페이지 이동 될때마다 메모리 사용량이 올라가며,
동영상 페이지를 많이 열수록 사용량이 급증하는 현상이 나타납니다.

4. 메모리 사용량이 100MB 전후로 로딩이 길어지거나, 혹은 프로그램이 멈추는 현상이 발생 합니다.

아래는 메모리 사용량 캡쳐 화면 입니다.
![default](https://cloud.githubusercontent.com/assets/23732865/20617018/9ef7dac4-b329-11e6-9a5b-1566c9e640be.png)

**Comment by realmani0** [comment]
- 자식창을 열경우 메모리를 최적화시킴
- 특정 동영상 플레이에서 멈추는 현상으로 다시 인코딩으로 문제점이 없어짐.
