### ISSUE TITLE
 PDF, HWP 파일이 열리지 않는 현상

### ISSUE THREAD

**Issue by hi763** [realmani0/special_CD#5]
내부 검수시에는 해당 현상이 나타나지 않았습니다. 

[업체 수정 요청 사항]
-> html에서 다음과 같이 파일을 열 때 파일이 열리지 않고 멈추는 현상이 발생합니다.
재현 경로: 실행 -> "1. 사무 장비 사용" -> "[1단원] 사무용품 사용" -> "[교과서] 1영역 PDF 파일" 돋보기 버튼 클릭 -> "파일 보기" 버튼
-> 아래와 같이 함수가 호출될 때 발생하는 문제로 파악됩니다. 혹시 호출 방법이 문제가 있다면 말씀 주세요.
주소: javascript:window.external.CallFolderOpen('data\\Lesson5\\step14\\pdf\\사무지원교과서-5영역.pdf')
-> 개발 PC 4대(Windows 7 2대, Windows 10 2대)에서 발생하지 않아 저희도 현상 파악에 애를 먹은 이슈입니다.
-> 7분 선생님들 중에서 3분 선생님 PC에서 발생합니다. 발생하는 PC에서는 100%의 빈도로 발생하고, 발생하지 않는 PC에서는 0%로 전혀 발생하지 않습니다.

**Comment by realmani0** [comment]
환경 및 현상 재현이 필요합니다.
확인이 불가능하여 테스트에 어려움이 있습니다.
