### ISSUE TITLE
바이러스 인식 관련

### ISSUE THREAD

**Issue by hi763** [realmani0/special_CD#6]
1. nProtect에서 생기는 현상은 수정 완료

2. INISAFE 에서 바이러스 인식 현상 발생

보안 업체에 따라 해당 현상이 나타날 수 있을 것 같아서, 해당 부분은 추가 테스트를 진행하도록 하겠습니다.

**Comment by hi763** [comment]
[내용 추가]

업체에 확인을 해보니 INISAFE 에서는 따로 바이러스로 인식 하는 것이 아니라
1. 파일 실행시 지속적으로 웹페이지 복구 에러가 발생
2. 이제 따라 INISAFE SANDBOX , INISAFE SFILTER삭제 후 pdf나 hwp 파일이 열렸다고 합니다.

**Comment by realmani0** [comment]
현상 재현이 안되는관계로..
현상 재현을 하거나 캡쳐 화면이 필요합니다
